### ISSUE TITLE
[Enhancement] feature request in ov

### ISSUE THREAD

**Issue by ciscohack** [noborus/ov#142]
Hello Expert,

One feature request if possible and if you could enable space key press to scroll the file as all other existing pager doing... i know you have key binding to achieve the task but it is good to have by default second if you could add ctrl + > and ctrl + < key bind to jump directly on top and bottom of page this is also available by default in all the pager programs rest all looks good so far ...

I tried the keybinding for page_up/page_down with space and other key combination but result is not what i am expecting . Second i also noticed ov line number is wasting unnecessary terminal space need to be optimised. Below screenshot you can see this space can be reduced when line number enabled.

![image](https://user-images.githubusercontent.com/11479557/152311216-14b83be5-96f8-4875-973f-598a7ca22ad5.png)

**Comment by noborus** [comment]
Thank you for writing the issue.
I noticed that the settings in ov-less.yml need to be modified for `>` and `<`.
I will commit the following later.
("CTRL +>" cannot be assigned due to terminal restrictions.)

```
diff --git a/ov-less.yaml b/ov-less.yaml
index 8bbe4a2..08f9f23 100644
--- a/ov-less.yaml
+++ b/ov-less.yaml
@@ -93,8 +93,10 @@ KeyBind:
         - "Up"
     top:
         - "Home"
+        - "<"
     bottom:
         - "End"
+        - ">"
     left:
         - "left"
     right:
@@ -127,9 +129,9 @@ KeyBind:
     remove_all_mark:
         - "ctrl+delete"
     next_mark:
-        - ">"
+        - "alt+>"
     previous_mark:
-        - "<"
+        - "alt+<"
     set_view_mode:
         - "p"
         - "P"
 ```
The line numbers in ov (displayed with ov -n) are just the width of the largest line number column, with no extra spaces.
(In large files, the first line will appear to have spaces).

Regarding line numbers, I would be grateful if you could raise another issue if necessary.

**Comment by ciscohack** [comment]
@noborus  Thanks for looking into it. it would be good if these basic task we handled without key map binding ov-less.xml config later if someone want to change the mapping they use the config to do. I hope you come up with some idea.  regarding line width i got your point but still if my text has not 5 digit number then no point to have extra width which take but space .. line number column should be surpassed and not take much terminal space

**Comment by noborus** [comment]
Many of the keys that are said to be standard follow `less`.
If the key binding of `ov` is the same as `less`, the key assignment of the function only in ov becomes difficult. 
Therefore, it is not the default.
However, for users accustomed to `less`, I maintain ov-less.yml.

**Comment by ciscohack** [comment]
> Many of the keys that are said to be standard follow `less`. If the key binding of `ov` is the same as `less`, the key assignment of the function only in ov becomes difficult. Therefore, it is not the default. However, for users accustomed to `less`, I maintain ov-less.yml.

Okay i then i tried key-map but i am not able to get result.. will check it later no issue

**Comment by noborus** [comment]
I'm done with mine, so I'll close it.
