### ISSUE TITLE
Ov takes extra space while line number enabled

### ISSUE THREAD

**Issue by ciscohack** [noborus/ov#143]
Hi Expert,

I have noticed OV is taking lot of terminal space when line number enabled. it would be good to surpasses the line number column width so when line number enable ov only take space as it required to save terminal width for other useful purpose. Thanks

**Comment by noborus** [comment]
The line number of ov is intended to be the minimum width to display the maximum number of digits.
Is it displayed like this?
Or do you think you want to narrow this width?
![ov-num](https://user-images.githubusercontent.com/2296563/152336919-da1ce2cb-85c3-46c8-9e44-3007f9f21b67.png)

**Comment by ciscohack** [comment]
Okay in my case i opened a log file which has only 100 lines even though it use large width. This log is having 171 lines i don't know whether this space is okay or not but for me it's waste of space so i keep number line off

![image](https://user-images.githubusercontent.com/11479557/152364575-28b5595e-d047-479f-a963-103527eddc2b.png)

**Comment by noborus** [comment]
Close as answered.
