### ISSUE TITLE
OV pager has small latency 

### ISSUE THREAD

**Issue by ciscohack** [noborus/ov#144]
Hi Expert,

I have syntax highlighter enable for my terminal app by using Chromaterm tool and i have noticed while reading log and syntax highlighter enable ov is having some latency so syntax highlight is taking some delay to trigger where as if i use less/moar/bat pager i do not have this behaviour.

**Comment by noborus** [comment]
Thank you for writing the issue.
I think it's because the timing of drawing is too low, if the problem you reported occurs in follow mode.

The output of Chromaterm is subtly slow, so it will look slow unless you increase the number of draws.

I will consider making the following changes.
```
diff --git a/oviewer/event.go b/oviewer/event.go
index 8d91ec7..e7be786 100644
--- a/oviewer/event.go
+++ b/oviewer/event.go
@@ -206,7 +206,7 @@ func (root *Root) followAll() {
 
 // updateInterval calls eventUpdate at regular intervals.
 func (root *Root) updateInterval(ctx context.Context) {
-	timer := time.NewTicker(time.Millisecond * 100)
+	timer := time.NewTicker(time.Millisecond * 50)
 	for {
 		select {
 		case <-timer.C:
```

**Comment by ciscohack** [comment]
> Thank you for writing the issue. I think it's because the timing of drawing is too low, if the problem you reported occurs in follow mode.
> 
> The output of Chromaterm is subtly slow, so it will look slow unless you increase the number of draws.
> 
> I will consider making the following changes.
> 
> ```
> diff --git a/oviewer/event.go b/oviewer/event.go
> index 8d91ec7..e7be786 100644
> --- a/oviewer/event.go
> +++ b/oviewer/event.go
> @@ -206,7 +206,7 @@ func (root *Root) followAll() {
>  
>  // updateInterval calls eventUpdate at regular intervals.
>  func (root *Root) updateInterval(ctx context.Context) {
> -	timer := time.NewTicker(time.Millisecond * 100)
> +	timer := time.NewTicker(time.Millisecond * 50)
>  	for {
>  		select {
>  		case <-timer.C:
> ```

No i am facing problem in normal log reading not using follow mode.. so feel in follow mode it would be even worse haven't try through but i tested the performance on bat/moar pager and no issue with that working flawless.. so some performance tweak we need on OV pager

**Comment by noborus** [comment]
> No i am facing problem in normal log reading not using follow mode.. so feel in follow mode it would be even worse haven't try through but i tested the performance on bat/moar pager and no issue with that working flawless.. so some performance tweak we need on OV pager

Hmm ...
It doesn't seem to be that slow in my environment.
It seems that we need to investigate a little more.
Can you tell me which os and terminal emulator you are using?

**Comment by ciscohack** [comment]
> > No i am facing problem in normal log reading not using follow mode.. so feel in follow mode it would be even worse haven't try through but i tested the performance on bat/moar pager and no issue with that working flawless.. so some performance tweak we need on OV pager
> 
> Hmm ... It doesn't seem to be that slow in my environment. It seems that we need to investigate a little more. Can you tell me which os and terminal emulator you are using?

I am running macOS 12.2 and terminal i use iterm2 and hyperterm. Chromaterm if you downloaded is having less trigger i have extended it with more trigger

**Comment by noborus** [comment]
Thank you.
I can't try it on a macOS, but it doesn't seem to cause problems.

**Comment by ciscohack** [comment]
i don't know how to help or show you. but Ov performance compare to moar and BAT pager is really very low and i am seeing the issue clearly all time ... rest all what Ov is offering is amazing and i love it becoz of it.  I hope you will some how able to repro and fix this performance issue. Thanks

**Comment by ciscohack** [comment]
Thanks @noborus. you mean to pull your latest ov and do manual compilation ..can you can you't add brew method to pull

**Comment by noborus** [comment]
`go test -bench` should be run where the source code is...
I would like to have the go compiler installed

```
brew install go
git clone https://github.com/noborus/ov.git
```

However, I may have understood the problem because someone else sent me the execution results.

Drawing tcell may be a little slow on macOS terminal. This is not easy to improve.

Ansi escape sequence parse is taking a long time in all environments. Even if the same color is used, it is interpreted each time. This can be improved.
I will work on improvement. Thank you very much.

**Comment by ciscohack** [comment]
@noborus my laptop under corporate policy and restriction facing some issue

**Comment by noborus** [comment]
Improved the speed of parser for all environments.

Another cause of slowness is using https://github.com/rivo/uniseg to count single character units.
This is slower than other software that ignores grapheme cluster, but I think it is necessary to support the new Unicode.

I will close this issue.

**Comment by ciscohack** [comment]
Finally you nailed it and in initial test performance looks much much better and smooth.. hope you address the scroll also with space click and jump to top and bottom also like other pager i requested in other thread

**Comment by noborus** [comment]
I don't make any further performance-improving changes to ov itself. 
It is better to improve [tcell](https://github.com/gdamore/tcell) and [uniseg](https://github.com/rivo/uniseg).

**Comment by ciscohack** [comment]
> I don't make any further performance-improving changes to ov itself. It is better to improve [tcell](https://github.com/gdamore/tcell) and [uniseg](https://github.com/rivo/uniseg).

sure no problem my job as a user to update you. I don't know how your ov implementation is differ then bat or moar pager tool but such performance issue is not there and they are fluid with syntax highlighter
