### ISSUE TITLE
Help is inconsistent regarding actual behaviour of [Home], [End] keys

### ISSUE THREAD

**Issue by bagohart** [noborus/ov#198]
Hi, cool project – tried it yesterday and instantly liked it!
The help has this entry:
```
[Home] * go to begin of line
[End]    * go to end of line
```
but when I press [Home] or [End], it moves the cursor to beginning/end of the current file, which also seems to be the default in less.
Is the documentation wrong or the implementation?
Is there another way to move the curser to beginning/end of line?

**Comment by noborus** [comment]
Thank you for the issue.

This is a mistake in help.
The move to the beginning of the file and the end of the file is correct.
There is currently no ability to move to the beginning and end of a line.
