### ISSUE TITLE
[Feature Request] Mark Toggle Keybind

### ISSUE THREAD

**Issue by p0da** [noborus/ov#209]
Would you consider simplifying the mark keybindings a bit by either adding a new mark keybind that allows users to toggle the setting of a mark, or changing the behavior of the current mark keybind to allow for toggling? Each press of the bind would be removing a mark if it already exists, or adding a mark if it does not already exist.

Also thanks for implementing https://github.com/noborus/ov/issues/206, it is very helpful.

**Comment by noborus** [comment]
Thank you for your request to ov.
I don't think the Mark feature will be implemented unless the user interface is better than the one suggested.
It's hard to undo a feature you've implemented, so you should be careful.

**Comment by p0da** [comment]
So perhaps adding an extra keybind (in addition to the existing "mark", "remove_mark", etc..) such as "toggle_mark" which allows users to toggle the existence of a mark on the current line would be the way to go? Or do you foresee an issue with that implementation?

**Comment by noborus** [comment]
I'm not keen on the mark function.
There is no mark function that I would like to resemble.
I think it's best to keep the use of the mark function to a minimum (no more unmarking).

**Comment by p0da** [comment]
Gotcha, thanks for considering
