### ISSUE TITLE
Make ov as golang package

### ISSUE THREAD

**Issue by varbhat** [noborus/ov#22]
Hey,there.

I would like to use ov in another application. Until,now,ov exists as standalone application. Can it be provided as golang package so that it can be used in other applications too?

**Comment by noborus** [comment]
Thank you for your interest in ov.
You can use oviewer as a package available from other applications.

Please use "github.com/noborus/ov/oviewer" as the import package.

Here's an example.
https://github.com/noborus/ov/blob/master/_example/simple/main.go

The public API can be found at the following.
https://pkg.go.dev/github.com/noborus/ov/oviewer
(The API may change.)

**Comment by varbhat** [comment]
Thank you very much for pointing it out.
