### ISSUE TITLE
Support offsetting search result (show context)

### ISSUE THREAD

**Issue by danieltd** [noborus/ov#220]
In `less`, there is the `--jump-target=n` option which allows the position of the given search result to be offset. Its function is described in the `less` man page: "...If any form of the -j option is used... forward searches (invoked with "n" or "N") begin at the line immediately after the target line, and repeated backward searches begin at the target line... For example, if '-j4' is used, the target line is the fourth line on the screen, so forward searches begin at the fifth line on the screen."

This feature is really useful when searching through the content being displayed on screen. Many times when I search for a term, I want to see the context that came before it along as what comes after. Thus, if the search term is scrolled to the vertical center of the screen (rather than the top), the user can see the lines that come both before and after the term. This is just one use-case for the `less` flag mentioned above. I rely on this feature daily, and it is one of the only things keeping me from completely switching from `less` to `ov`.

Consider the following example searching for the term 'search' using `less FILE_PATH`
![image](https://user-images.githubusercontent.com/2867646/202870575-59cd5615-8354-40ac-adcd-c4d78280ec52.png)

versus using `less -j .5 FILE_PATH`
![image](https://user-images.githubusercontent.com/2867646/202870593-ef33f236-2fe2-46db-a397-f2f78cd03469.png)

**Comment by noborus** [comment]
Thank you for your good issue.
I think this is a good idea.
