### ISSUE TITLE
Use $XDG_CONFIG_HOME instead of $HOME directory for configuration file

### ISSUE THREAD

**Issue by cmvanb** [noborus/ov#247]
Hello,

I like your pager software! Very cool.

I'm replacing less with ov. I need to configure ov for similar keybindings to less, so I added the configuration file `.ov.yaml`. I noticed that the program expects it to be in `$HOME` directory.

I understand this is a common place for unix software to place files, but it is cleaner if software follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). The default path for configuration files is then indicated by `$XDG_CONFIG_HOME`, the default value is `$HOME/.config/`.

This way, users have control over where software configuration files are located, and the dotfiles won't clutter the home directory.

Will you consider switching the default path for the configuration file?

If you wish, I can open a PR for this.

best regards

**Comment by noborus** [comment]
Thanks you.
I used [viper](https://github.com/spf13/viper) as is. you might be right.
If `ov` can be used even if $XDG_CONFIG_HOME takes precedence over $HOME, I would like to do so.

**Comment by cmvanb** [comment]
I opened a [PR](https://github.com/noborus/ov/pull/257) for this.

**Comment by cmvanb** [comment]
I think that's a good idea, the file name is cleaner. I will update the PR with your suggestion.

**Comment by noborus** [comment]
Great, thank you!
