### ISSUE TITLE
logfmt colums?

### ISSUE THREAD

**Issue by oderwat** [noborus/ov#271]
Would it be possible to detect or set the input parsing to process `logfmt` style text and create the columns (using the keys as head) on the fly? Afaik the output gets `re-rerendered` so it could be possible to deal with new keys that suddenly increase the number of columns. If this would be possible one would also probably want to have a filter to include/exclude columns base on the key names.

**Comment by noborus** [comment]
ov is a pager, so it doesn't render it, it just displays the line as is.
You will need another software to handle logfmt.
