### ISSUE TITLE
Please add support for rereading the current file when jumping to the end

### ISSUE THREAD

**Issue by hupfdule** [noborus/ov#32]
In less when jumping to the end of the file via `END` or `G` the file is also reread. That is very handy when viewing logfiles that grow while viewing them.

For example,

 - open a logfile
 - press `G` or `END` to jump to the end of the file
 - …
 - press `G` or `END` again

The second invocation (and in fact also the first invocation) would also display lines that were added to the file after step 2 (the first jump to the files end).

**Comment by noborus** [comment]
I think this is a good idea. :+1: 
I would like to implement it eventually, but I don't know if it's still a problem.

**Comment by hupfdule** [comment]
I would have thought that the actual rereading of the file would be easily solved (as I tried in #33):

```go
  root.Doc.ReadFile(root.Doc.FileName)
  root.viewSync()
  root.Screen.Sync()
```

But it seems that this is not the case. Do you know out of your head what would be necessary for this to happen?

**Comment by noborus** [comment]
The current ov does not assume Reload, so it will not work as it is.

You need to initialize slice and clear the cache for it to work.
There may be other problems as well.

```go
func (root *Root) ReRead() {
	root.Doc.lines = nil
	root.Doc.endNum = 0
	err := root.Doc.ReadFile(root.Doc.FileName)
	if err != nil {
		log.Println(err)
		return
	}
	root.Doc.ClearCache()
	root.viewSync()
}
```

**Comment by hupfdule** [comment]
Many thanks! This seems to work very well. I didn't find any issues with it yet.

I have taken the liberty to provide a PR for it: #34

**Comment by noborus** [comment]
I think I could implement it, so I'll close this issue.
Please reopen if there is a problem.
