### ISSUE TITLE
Last column is not fully displayed

### ISSUE THREAD

**Issue by aoyama-val** [noborus/ov#368]
# Problem

The last column is not fully displayed.
See that the value of the second column is truncated to the length of the first column.

![スクリーンショット 2023-06-03 21 49 31](https://github.com/noborus/ov/assets/13144822/d8cc8933-1932-41d3-84c7-ba06a196a21d)

# To reproduce

[sample.txt](https://github.com/noborus/ov/files/11642660/sample.txt)

```console
$ ov --config ~/.config/ov/psql.yaml --view-mode psql sample.txt
```

```psql.yaml
General:
  TabWidth: 4

Mode:
  psql:
    Header: 2
    AlternateRows: false
    ColumnMode: true
    LineNumMode: false
    WrapMode: false
    ColumnDelimiter: "|"
```

# Environment

- ov version 0.30.0 rev:ff0c648 from homebrew
- macOS

**Comment by noborus** [comment]
Thank you for your good issue.
I will fix this.
