### ISSUE TITLE
begin_left and end_right should change active column

### ISSUE THREAD

**Issue by aoyama-val** [noborus/ov#369]
Currently, begin_left and end_right don't change active column. That is, suppose the first column is active, press Shift-End and the last column is displayed, but the active column is still the first one, then press left and nothing happens (counter-intuitively!). I expected that the last -1 column would be active.
Is it possible to change this behavior or introduce new commands which scroll to beginning/end of line and set first/last column to be active?

**Comment by noborus** [comment]
I will consider.
This has concerns about the behavior when it starts or ends with a delimiter
and when the columns are misaligned.

**Comment by noborus** [comment]
Implemented. thank you.
