### ISSUE TITLE
How to disable wrap mode is not clear from the help

### ISSUE THREAD

**Issue by aoyama-val** [noborus/ov#370]
The help says:
```
  -w, --wrap                       wrap mode (default true)
```

but I had trouble finding the way to disable wrap mode.

```console
# NG
$ ov --wrap false sample.txt

# OK
$ ov --wrap=false sample.txt
```

If the help was something like this, it would be kinder:
```
  -w, --wrap=[true|false]                      wrap mode (default true)
```

**Comment by noborus** [comment]
Thank you for your issue.
This is confusing in how Cobra works and could be improved on Cobra's side. https://github.com/spf13/cobra/issues/1606

I didn't want to rewrite the help in a big way, so I decided to do it with a small fix.
It will be as follows.

```
  -w, --wrap[=true|=false]         wrap mode (default true)
```

**Comment by noborus** [comment]
I used SetUsageFunc to make it a customizable way because the previous PR had issues.
