### ISSUE TITLE
Feature request: support ansi and rgb color names

### ISSUE THREAD

**Issue by nkh** [noborus/ov#423]
for cavemen (and women) like me who have difficulties remembering what [Cornflower Blue](https://en.wikipedia.org/wiki/Cornflower_blue) is for color.

https://www.ditig.com/256-colors-cheat-sheet

Maybe names like 
```
ansi<number>
rgb<R><G><B>
```

**Comment by noborus** [comment]
`ov` uses the color specification of tcell as it is
You can also specify something like "#2a2a2a".

https://github.com/noborus/ov#style-customization

Let me know if this is not enough.

**Comment by nkh** [comment]
ANSI 256 colors is more practical and is used in many other packages but if the lib you're using doesn't support it then what you wrote above is fine and please close this ticket.

**Comment by noborus** [comment]
I'll close it.Please reopen if necessary.
