### ISSUE TITLE
Scroll past end

### ISSUE THREAD

**Issue by 89z** [noborus/ov#45]
If I use this program:

~~~go
package main

import (
   "github.com/tigrawap/slit"
   "log"
)

const s = `
  [Enter], [Down], [ctrl+N]  * forward by one line
  [Up], [ctrl+p]             * backward by one line
  [Home]                     * go to begin of line
  [End]                      * go to end of line
`

func main() {
   c := make(chan string)
   o, e := slit.NewFromStream(c)
   if e != nil {
      log.Fatal(e)
   }
   c <- s
   o.Display()
}
~~~

and enter `/line`, `Enter`, `n`, `n`, `n`, it takes me to last result, which look
like this:

> ![Untitled](https://user-images.githubusercontent.com/73562167/103119960-5485c600-463b-11eb-8082-83332ace8ba4.png)

it puts it at the top of the screen. But this program:

~~~go
package main

import (
   "bytes"
   "github.com/noborus/ov/oviewer"
   "io/ioutil"
   "log"
)

const s = `
  [Enter], [Down], [ctrl+N]  * forward by one line
  [Up], [ctrl+p]             * backward by one line
  [Home]                     * go to begin of line
  [End]                      * go to end of line
`

func main() {
   doc, err := oviewer.NewDocument()
   if err != nil {
      log.Fatal(err)
   }
   doc.ReadAll(ioutil.NopCloser(bytes.NewBufferString(s)))
   ov, err := oviewer.NewOviewer(doc)
   if err != nil {
      log.Fatal(err)
   }
   if err := ov.Run(); err != nil {
      log.Fatal(err)
   }
}
~~~

wont do that. It wont let you scroll past the end, so you get this:

> ![a](https://user-images.githubusercontent.com/73562167/103120014-89921880-463b-11eb-9688-ed4346dc0ecd.png)

**Comment by noborus** [comment]
This is the intended specification, but may be changed.
This change requires a little time.

**Comment by 89z** [comment]
yes thank you

This is also the behavior of Less https://wikipedia.org/wiki/Less_(Unix)
