### ISSUE TITLE
Flickering while loading lines

### ISSUE THREAD

**Issue by Crissante** [noborus/ov#452]
When used on a file with many lines there is flickering while the lines load until it is fully loaded

**Comment by noborus** [comment]
Thank you for the issue.
This issue requires environmental information. 
Please tell me the OS and terminal emulator software.

I think that depending on the environment, the combination of [tcell](https://github.com/gdamore/tcell)
and `terminal emulator software` may cause the entire page to be redisplayed
without being able to change just a part of it.

**Comment by Crissante** [comment]
This occurs on a Windows 10 host + Ubuntu on WSL + Windows Terminal

**Comment by Crissante** [comment]
Do you have access to a similar setup @noborus? Any more information you'd need?

**Comment by noborus** [comment]
Thank you for information.
I tried.
Flickering occurred in Windows Terminal v1.17.11461.0.
Flickering did not occur in Windows Terminal v1.18.2681.0.
Using the latest version seems to resolve it.

Support for devices that do not support some rewriting will be considered separately.
thank you very much.

**Comment by Crissante** [comment]
Thanks @noborus!
