### ISSUE TITLE
Option of horizontal scroll amount

### ISSUE THREAD

**Issue by aoyama-val** [noborus/ov#460]
Currently `left` and `right` commands scroll one column by one, so it takes time to scroll very long lines. It would be so nice if  this was configurable. `less` has the option for it:

       -# or --shift
              Specifies the default number of positions to scroll
              horizontally in the RIGHTARROW and LEFTARROW commands.  If
              the number specified is zero, it sets the default number
              of positions to one half of the screen width.
              Alternately, the number may be specified as a fraction of
              the width of the screen, starting with a decimal point: .5
              is half of the screen width, .3 is three tenths of the
              screen width, and so on.  If the number is specified as a
              fraction, the actual number of scroll positions is
              recalculated if the terminal window is resized.

Thanks for the tool. I've been using it for months and now I really like it!

**Comment by noborus** [comment]
Thank you for the issue.

I think it's a good idea to add a shift (equivalent) option.
I'm considering implementing it, but I'm thinking of changing it slightly from `less`.

Currently, for horizontal scrolling, in addition to the left and right keys that move by one width, there is also half-screen scrolling using ctrl+left and ctrl+right.
In addition to this, I am planning to add horizontal scrolling of the shift width set by ctrl+shift+left and ctrl+shift+right.
This can be changed to left or right by setting the key binding, so it can also be set to remain the same as `less`.

**Comment by noborus** [comment]
I have [released](https://github.com/noborus/ov/releases/tag/v0.33.0) the implemented version, so I will close it.
