### ISSUE TITLE
FYI: ArchLinux now has three ‘flavours’ of ov

### ISSUE THREAD

**Issue by kseistrup** [noborus/ov#470]
This issue is informative only. No action is needed unless you wish to include the information in the README.

ArchLinux User Repository now has three different flavours of `ov`, with each their own maintainer. They cater to different audiences:

### `ov`

Compile at install time from latest stable release:
* https://aur.archlinux.org/packages/ov

### `ov-bin`

Install latest stable binary from the release page (compilation not necessesary):
* https://aur.archlinux.org/packages/ov-bin

### `ov-git`

Compile at install time from latest git commit:
* https://aur.archlinux.org/packages/ov-git

As mentioned in #245, they can all be installed using an AUR helper:
* https://wiki.archlinux.org/title/AUR_helpers

**Comment by noborus** [comment]
Thank you for the wonderful information.
Is it possible to send a pull request to README.md?

**Comment by kseistrup** [comment]
I'll see what I can do.
