### ISSUE TITLE
Exit without clear screen

### ISSUE THREAD

**Issue by 89z** [noborus/ov#48]
Currently the screen is always cleared on exit:

https://github.com/noborus/ov/blob/c1ca769f8805e842688c89328084be97c794c62e/oviewer/oviewer.go#L365

Sometimes it would be preferable to keep the screen contents on exit. Other tools like Less offer this via option `-X` or environment variable `LESS=X`:

https://serverfault.com/questions/785949

**Comment by noborus** [comment]
If you do not clear the tcell display, it will look good on the display, but in reality it will differ in parts such as line breaks.

Therefore, ov provides a mode to write out the displayed line at the end and end it.

**Comment by 89z** [comment]
> Therefore, ov provides a mode to write out the displayed line at the end and
> end it.

Are you talking about `WriteQuit`? I tried this but it didnt output anything:

~~~
package main

import (
   "bytes"
   "github.com/noborus/ov/oviewer"
   "io/ioutil"
   "log"
)

const s = `[Enter], [Down], [ctrl+N]  * forward by one line
[Up], [ctrl+p]             * backward by one line
[Home]                     * go to begin of line
[End]                      * go to end of line`

func main() {
   doc, err := oviewer.NewDocument()
   if err != nil {
      log.Fatal(err)
   }
   doc.ReadAll(ioutil.NopCloser(bytes.NewBufferString(s)))
   ov, err := oviewer.NewOviewer(doc)
   if err != nil {
      log.Fatal(err)
   }
   ov.WriteQuit()
}
~~~

**Comment by 89z** [comment]
This seems to do it:

~~~go
package main

import (
   "github.com/noborus/ov/oviewer"
   "io"
   "log"
   "strings"
)

const s = `[Enter], [Down], [ctrl+N]  * forward by one line
[Up], [ctrl+p]             * backward by one line
[Home]                     * go to begin of line
[End]                      * go to end of line`

func main() {
   d, e := oviewer.NewDocument()
   if e != nil {
      log.Fatal(e)
   }
   d.ReadAll(io.NopCloser(strings.NewReader(s)))
   v, e := oviewer.NewOviewer(d)
   if e != nil {
      log.Fatal(e)
   }
   v.Run()
   v.WriteOriginal()
}
~~~

https://pkg.go.dev/github.com/noborus/ov/oviewer#Root.WriteOriginal

**Comment by aranjan7** [comment]
@89z WriteOriginal() seems to print only the last page displayed. -X option prints all pages till :Q is typed. Is there any workaround to have less like behavior. thank you

**Comment by 89z** [comment]
I dont use a pager anymore, as its ultimately a poor solution for a GUI need. Instead I have switched to using a local server with html/template [1]. However I will reopen this issue in case others want to work on it.

https://godocs.io/html/template

**Comment by noborus** [comment]
I'm not thinking of adding it just to make it the same as `less`.
The same behavior as `less` is difficult, and I need another reason to add it.

**Comment by aranjan7** [comment]
I put this minor change (add a public API) to fix this. See if it makes sense to merge @noborus .. thanks
https://github.com/noborus/ov/pull/146
