### ISSUE TITLE
pasting text into search truncates text

### ISSUE THREAD

**Issue by iloveitaly** [noborus/ov#486]
Here's an example:
![Code - README md](https://github.com/noborus/ov/assets/150855/8e844895-7efc-4bd9-b566-6eb9763789de)

Pasting text truncates part of the search query. Seems to do better on second paste.

**Comment by noborus** [comment]
Thank you for the issue.
I haven't been able to reproduce it myself, but I think it's possible.
This is most likely a problem with the library you are using, so it may take some time to resolve.

You might try disabling mouse support.
https://github.com/noborus/ov?tab=readme-ov-file#319-mouse-support

**Comment by iloveitaly** [comment]
I'm using tmux—do you think that has something to do with it?

I'll try disabling mouse mode.

**Comment by iloveitaly** [comment]
Tried disabling mouse support, didn't fix it.

Tried in a plain old zsh terminal (no tmux), didn't fix it either.

So odd! Any other ideas?

**Comment by noborus** [comment]
sorry. #613 may be involved.
If `--incsearch = f` works well, fix it in the next version.

**Comment by iloveitaly** [comment]
Awesome! It's fixed!!
