### ISSUE TITLE
Feature request: display only lines matching a pattern

### ISSUE THREAD

**Issue by prajnoha** [noborus/ov#493]
It would be great if it was possible to filter lines so they contain only the lines that match a defined pattern. This would be similar to `less` and its `&pattern` feature. In addition to that, `ov` could also accept that pattern as a command line argument and do the filtering from the very start of `ov`'s execution. It should also work with all the `--follow-*` modes.

This way, we could omit the use of `grep` and similar in the middle of a pipeline like: `<some command> | grep --line-buffered pattern | ov --follow-mode`

**Comment by noborus** [comment]
Implemented in v0.34.0.
thank you very much.
https://github.com/noborus/ov/releases/tag/v0.34.0

**Comment by prajnoha** [comment]
Great, thank you!
