### ISSUE TITLE
Feature Request: add CI to the workflow

### ISSUE THREAD

**Issue by ccoVeille** [noborus/ov#527]
The CI should include at least a validation of the unit tests

Later, we could add `golangci-lint` to it, when code would be saner

**Comment by noborus** [comment]
sorry. This has already been fixed as the github actions test didn't work last time.

https://github.com/noborus/ov/blob/4a67425af3e57e8610bcf438aac809e6f5b90aad/.github/workflows/build.yml

https://github.com/noborus/ov/actions
