### ISSUE TITLE
Enable parse command line options in the config files

### ISSUE THREAD

**Issue by XhstormR** [noborus/ov#544]
Is there a way to put command line options into a config file? 

If possible, I don't need to configure options in various places. Currently, I need to configure ov's CLI options in delta, bat and nnn respectively， for example the `-F` options.

**Comment by noborus** [comment]
Thank you for your question.

> Is there a way to put command line options into a config file?
> 
> If possible, I don't need to configure options in various places. Currently, I need to configure ov's CLI options in delta, bat > and nnn respectively， for example the -F options.

yes. For settings equivalent to '-F', set the following at the top of yaml.

```yaml
QuitSmall: true
```

It was missing from the documentation, so I'll add it. thank you!
