### ISSUE TITLE
[REQ] Follow mode

### ISSUE THREAD

**Issue by blurayne** [noborus/ov#57]
If I do:

```bash
(while :; do echo random-$RANDOM; sleep 0.01; done;) | ov  
```

The bottom status line shows STDIN and stops at 100 lines and it doesn't matter what terminal size I use or whether I have interacted with the page. Using the sync-hotkey didn't do anything. This behavior is odd.

Is there a "follow mode" planned?

--
Anyway, very good  pager! I like it very much!

**Comment by noborus** [comment]
Thank you so much!

> Is there a "follow mode" planned?

Yes. I plan to follow mode.
The example in this issue made me aware of the current bug.
Thank you.

**Comment by noborus** [comment]
#58 fixed stdin to read continuously (because it doesn't reach EOF).
However, files that reach EOF cannot yet be read (like tail -f).
I will fix this in the future.
