### ISSUE TITLE
Piping ov to ov breaks commands and terminal

### ISSUE THREAD

**Issue by KapJI** [noborus/ov#634]
## Repro
```
> ov file | ov
```
Then type `/private`.

**Expected behaviour:** `private` is searched. First `ov` prints output to stdout and doesn't affect the next call.
**Actual behaviour:** Mode selection menu appears when `p` is pressed. Unable to exit with `q`, terminal session is corrupted. It seems both processes are reading commands and interfering with each other.

Without piping it works fine.

## Why I need to pass ov to ov?
I have some tools which are configured to use `ov` by default, e.g. I want this: `delta --help | bat -l help`.
`less` handles such case fine.

## Info
```
> ov --version
ov version 0.36.0 rev:d671c94
```
Platforms: MacOS, Linux

**Comment by noborus** [comment]
Thank you for Issue.

This is certainly a problem.
I want to redirect the `ov` while displaying it on the screen, but if it starts twice, there will be problems.

**Comment by noborus** [comment]
Changed so that the screen is not displayed when output is redirected.
The `--force-screen` option is now required to display the screen.

**Comment by KapJI** [comment]
Thanks! I built it from sources and this case with piping works now.
