### ISSUE TITLE
Version and .deb

### ISSUE THREAD

**Issue by azlux** [noborus/ov#636]
Hi,
On one of your user demand,
I've added the `ov` `.deb` file into my repository https://packages.azlux.fr/

The issue is the .deb have the version `1:XXXX` instead of the good version from the github release.

```bash
root@packages:~$ dpkg-deb -I ov_0.36.0-1_amd64.deb
 new Debian package, version 2.0.
 size 6664752 bytes: control archive=370 bytes.
       1 bytes,     0 lines      conffiles
     238 bytes,     9 lines      control
      47 bytes,     1 lines      md5sums
 Package: ov
 Version: 1:0.36.0
 Section:
 Priority: optional
 Architecture: amd64
 Maintainer: Noboru Saito <noborusai@gmail.com>
 Installed-Size: 12078
 Homepage: https://github.com/noborus/ov
 Description: ov is a feature rich terminal pager.
```

To have a good consistency, the version number should be the exact same as the release one.

Best regards
Azlux

**Comment by noborus** [comment]
Thanks for the issue.

I think #637 will fix it.

Please let me know if you have any problems.
