### ISSUE TITLE
Down moves two lines instead of one

### ISSUE THREAD

**Issue by 89z** [noborus/ov#76]
When you press `Down`, `actionMoveDown` is used:

https://github.com/noborus/ov/blob/98f0ab6828e9d4455616a79cd55e66abcce42512/oviewer/keybind.go#L115

which calls `root.moveDown`:

https://github.com/noborus/ov/blob/98f0ab6828e9d4455616a79cd55e66abcce42512/oviewer/keybind.go#L66

which is supposed to move the screen down one line:

https://github.com/noborus/ov/blob/98f0ab6828e9d4455616a79cd55e66abcce42512/oviewer/move.go#L196-L197

However using this file:

~~~go
package oviewer

import (
   "bytes"
   "fmt"
   "testing"
)

func TestDown(t *testing.T) {
   b := new(bytes.Buffer)
   for n := range [99]struct{}{} {
      fmt.Fprintln(b, n)
   }
   r, e := NewRoot(b)
   if e != nil {
      t.Error(e)
   }
   r.Run()
}
~~~

I noticed that each press of `Down` moves the screen two lines.

**Comment by noborus** [comment]
Thank you very much.
There was a bug in the move when it was not in wrap mode.

**Comment by 89z** [comment]
https://github.com/noborus/ov/pull/77
