### ISSUE TITLE
Mouse select fails on newlines

### ISSUE THREAD

**Issue by 89z** [noborus/ov#81]
Using this program:

~~~go
package main

import (
   "bytes"
   "fmt"
   "github.com/noborus/ov/oviewer"
)

func main() {
   b := new(bytes.Buffer)
   for n := range [99]struct{}{} {
      fmt.Fprintln(b, n)
   }
   r, e := oviewer.NewRoot(b)
   if e != nil {
      panic(e)
   }
   r.Run()
}
~~~

Start the pager, select first two lines with mouse, then paste somewhere else, the newline is removed:

~~~
0                                                                                  1
~~~

**Comment by 89z** [comment]
As a workaround, `WriteOriginal` seems to allow normal copy paste after program exit:

~~~go
package main

import (
   "bytes"
   "fmt"
   "github.com/noborus/ov/oviewer"
)

func main() {
   b := new(bytes.Buffer)
   for n := range [99]struct{}{} {
      fmt.Fprintln(b, n)
   }
   r, e := oviewer.NewRoot(b)
   if e != nil {
      panic(e)
   }
   r.Run()
   r.WriteOriginal()
}
~~~

**Comment by 89z** [comment]
Looks like this is not an issue with Ov

**Comment by noborus** [comment]
This is an issue for the ov.
ov supports copying multiple lines with the mouse, but there seems to be a problem with windows.
It's just a windows problem and I don't know how to solve it right now.

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/9933
